import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })
import MainLayout from '../layout/MainLayout/MainLayout'
import ArbreTableau from '../components/ArbreTableau/ArbreTableau'

export default function Home() {

  const [listUser,setListUser] = React.useState([{id:42, pseudo: "ValCMoi"}])
  const [currentNewUser, setNewCurrentUser] = React.useState({id:Math.floor(Math.random()* 1000000), pseudo:""})

  const addUserToList = () => {
    setListUser([...listUser, currentNewUser])
    setNewCurrentUser({id:Math.floor(Math.random() * 10000000), pseudo:''})
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <MainLayout>

        <ArbreTableau/>

      </MainLayout>

      </main>
    </>
  )
}
